env:
  global:
    - CODECOV_ID=017a4ebc-080c-4947-81e4-253f2294a5d0
    - CC_TEST_REPORTER_ID=7f97b09b52df4212c66f57cc09bdc7e3225161c2c6b149012a0b1335616b8831

language: java

jdk: openjdk13

before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.zip
  - unzip -qq apache-maven-3.5.4-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.5.4
  - export PATH=$M2_HOME/bin:$PATH
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - sudo fc-cache -f -v
  #- export DISPLAY=:99.0                # Display number for xvfb (for headless browser testing)
  #- sh -e /etc/init.d/xvfb start        # Start xvfb (for headless browser testing)

install: true

services:
  - xvfb

script:
  - mvn clean install -Pci
# Specify a display with xvfb for UI testing

after_script:
  - JACOCO_SOURCE_PATH=./src/main/java ./cc-test-reporter format-coverage ./target/coverage-reports/jacoco.xml -t jacoco -o ./target/coverage/codeclimate.json
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage -i ./target/coverage/codeclimate.json; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
