/**
* ===========================================
* PDF Forms Designer
* ===========================================
*
* Project Info:  http://pdfformsdesigne.sourceforge.net
* (C) Copyright 2006-2008..
* Lead Developer: Simon Barnett (n6vale@googlemail.com)
*
* 	This file is part of the PDF Forms Designer
*
    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    General Public License for more details.

    You should have received a copy of the GNU General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


*
* ---------------
* RadioButtonFieldPanel.java
* ---------------
*/
package org.pdf.forms.gui.properties.object.field;

import java.awt.event.ActionListener;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFrame;

import org.pdf.forms.document.Page;
import org.pdf.forms.gui.IMainFrame;
import org.pdf.forms.gui.designer.IDesigner;
import org.pdf.forms.gui.windows.RadioButtonGroupOrganiser;
import org.pdf.forms.utils.XMLUtils;
import org.pdf.forms.widgets.ButtonGroup;
import org.pdf.forms.widgets.CheckBoxWidget;
import org.pdf.forms.widgets.IWidget;
import org.pdf.forms.widgets.RadioButtonWidget;
import org.w3c.dom.Element;

public class RadioButtonFieldPanel extends javax.swing.JPanel {
    private Map widgetsAndProperties;

    private IDesigner designerPanel;
    private List buttonGroups;
    private int type;

    /**
     * Creates new form RadioButtonFieldPanel
     */
    public RadioButtonFieldPanel() {
        initComponents();
    }

    public void setDesignerPanel(IDesigner designerPanel, int type) {
        this.designerPanel = designerPanel;
        this.type = type;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        appearanceBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonGroupBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        appearanceBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"None", "Underline", "Solid", "Sunken Box", "Custom..."}));
        appearanceBox.setEnabled(false);

        jLabel1.setText("Apperance:");
        jLabel1.setEnabled(false);

        jLabel2.setText("Radio Button Group:");

        buttonGroupBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonGroup(evt);
            }
        });

        jButton1.setText("Organise");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organiseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(layout.createSequentialGroup()
                                        .add(jLabel1)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(appearanceBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(layout.createSequentialGroup()
                                .add(jLabel2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jButton1)
                                .add(buttonGroupBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabel1)
                                .add(appearanceBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabel2)
                                .add(buttonGroupBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton1)
                        .addContainerGap(214, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void organiseClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organiseClicked
        JDialog dialog = new JDialog();
        IMainFrame mainFrame = designerPanel.getMainFrame();
        List widgets = mainFrame.getFormsDocument().getPage(mainFrame.getCurrentPage()).getWidgets();

        RadioButtonGroupOrganiser radioButtonGroupOrgansier = new RadioButtonGroupOrganiser(dialog, buttonGroups,
                widgets, type);

        dialog.getContentPane().add(radioButtonGroupOrgansier);
        dialog.setModal(true);
        dialog.pack();
        dialog.setLocationRelativeTo((JFrame) mainFrame);
        dialog.setVisible(true);

        populateButtonGroups();

        setProperties(widgetsAndProperties);
    }//GEN-LAST:event_organiseClicked

    private void updateButtonGroup(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonGroup
        for (Iterator it = widgetsAndProperties.keySet().iterator(); it.hasNext();) {
        	
        	IWidget widget;
        	if(type == IWidget.RADIO_BUTTON){
        		RadioButtonWidget radioButtonWidget = (RadioButtonWidget) it.next();
        		radioButtonWidget.setRadioButtonGroupName((String) buttonGroupBox.getSelectedItem());
        		
        		widget = radioButtonWidget;
        	} else {
        		CheckBoxWidget checkBoxWidget = (CheckBoxWidget) it.next();
        		checkBoxWidget.setCheckBoxGroupName((String) buttonGroupBox.getSelectedItem());
        		
        		widget = checkBoxWidget;
        	}

            Element objectProperties = widget.getProperties().getDocumentElement();
            Element defaultElement = XMLUtils.getPropertyElement(objectProperties, "Default");
            defaultElement.getAttributeNode("value").setValue("Off");
            widget.setObjectProperties(objectProperties);
        }

        designerPanel.repaint();
    }//GEN-LAST:event_updateButtonGroup

    public void setProperties(Map widgetsAndProperties) {
        this.widgetsAndProperties = widgetsAndProperties;

        String buttonGroupToUse = null;

        IMainFrame mainFrame = designerPanel.getMainFrame();
        Page page = mainFrame.getFormsDocument().getPage(mainFrame.getCurrentPage());

        switch (this.type) {
            case IWidget.RADIO_BUTTON:
                this.buttonGroups = page.getRadioButtonGroups();

                break;
            case IWidget.CHECK_BOX:
                this.buttonGroups = page.getCheckBoxGroups();

                break;
        }

        populateButtonGroups();

        /** iterate through the widgets */
        for (Iterator it = widgetsAndProperties.keySet().iterator(); it.hasNext();) {
            IWidget widget = (IWidget) it.next();

            Element objectPropertiesElement = (Element) widgetsAndProperties.get(widget);
            
            /** add field propertes */
	        Element fieldProperties = (Element) objectPropertiesElement.getElementsByTagName("field").item(0);

            String buttonGroup = XMLUtils.getAttributeFromChildElement(fieldProperties, "Group Name");

            if (buttonGroupToUse == null) { // this must be the first time round
                buttonGroupToUse = buttonGroup;
            } else { // check for subsequent widgets
                if (!buttonGroupToUse.equals(buttonGroup)) {
                    buttonGroupToUse = "mixed";
                }
            }

            setComboValue(buttonGroupBox, buttonGroupToUse.equals("mixed") ? null : buttonGroupToUse);
        }
    }

    private void populateButtonGroups() {
        ActionListener listener = buttonGroupBox.getActionListeners()[0];
        buttonGroupBox.removeActionListener(listener);

        buttonGroupBox.removeAllItems();
        for (Iterator it = buttonGroups.iterator(); it.hasNext();) {
            ButtonGroup buttonGroup = (ButtonGroup) it.next();
            buttonGroupBox.addItem(buttonGroup.getName());
        }

        buttonGroupBox.addActionListener(listener);
    }

    private void setComboValue(JComboBox comboBox, Object value) {
        ActionListener listener = comboBox.getActionListeners()[0];
        comboBox.removeActionListener(listener);

        if (value instanceof Integer) {
            comboBox.setSelectedIndex(((Integer) value).intValue());
        } else {
            comboBox.setSelectedItem(value);
        }

        comboBox.addActionListener(listener);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox appearanceBox;
    private javax.swing.JComboBox buttonGroupBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
