/**
 * ===========================================
 * PDF Forms Designer
 * ===========================================
 *
 * Project Info:  http://pdfformsdesigne.sourceforge.net
 * (C) Copyright 2006-2008..
 * Lead Developer: Simon Barnett (n6vale@googlemail.com)
 *
 * 	This file is part of the PDF Forms Designer
 *
 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 This library is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 General Public License for more details.

 You should have received a copy of the GNU General Public
 License along with this library; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


 *
 * ---------------
 * BorderPropertiesPanel.java
 * ---------------
 */
package org.pdf.forms.gui.properties.border;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;

import org.pdf.forms.gui.designer.IDesigner;
import org.pdf.forms.gui.designer.gui.Rule;
import org.pdf.forms.utils.XMLUtils;
import org.pdf.forms.widgets.IWidget;
import org.w3c.dom.Element;

public class BorderPropertiesPanel extends JPanel {

    private IDesigner designerPanel;
    private Map widgetsAndProperties;

    private final int units = (int) (Rule.INCH / 2.54);

    /**
     * Creates new form BorderPropertiesPanel
     */
    public BorderPropertiesPanel() {
        initComponents();
    }

    public void setDesignerPanel(IDesigner designerPanel) {
        this.designerPanel = designerPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        leftEdgesIcon = new javax.swing.JLabel();
        borderStyleBox = new javax.swing.JComboBox();
        borderWidthBox = new javax.swing.JTextField();
        borderColorButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        backgroundFillBox = new javax.swing.JComboBox();
        backgroundFillColorButton = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Borders"));

        leftEdgesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/pdf/forms/res/Border Together.png"))); // NOI18N
        leftEdgesIcon.setOpaque(true);

        borderStyleBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"None", "Solid", "Beveled"}));
        borderStyleBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBorderStyle(evt);
            }
        });

        borderWidthBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                updateBorderSize(evt);
            }
        });

        borderColorButton.setContentAreaFilled(false);
        borderColorButton.setOpaque(true);
        borderColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borderColorButtonClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                .add(12, 12, 12)
                                .add(leftEdgesIcon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(borderStyleBox, 0, 135, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(borderWidthBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(borderColorButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(jPanel1Layout.createSequentialGroup()
                                                .add(leftEdgesIcon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(4, 4, 4))
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                                .add(borderColorButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(borderStyleBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(borderWidthBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Background Fill"));

        jLabel6.setText("Style:");

        backgroundFillBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"None", "Solid"}));
        backgroundFillBox.setEnabled(false);
        backgroundFillBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFillStyle(evt);
            }
        });

        backgroundFillColorButton.setEnabled(false);
        backgroundFillColorButton.setContentAreaFilled(false);
        backgroundFillColorButton.setOpaque(true);
        backgroundFillColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillColorClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel2Layout.createSequentialGroup()
                                .add(jLabel6)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(backgroundFillBox, 0, 191, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(backgroundFillColorButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel2Layout.createSequentialGroup()
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(jLabel6)
                                        .add(backgroundFillColorButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(backgroundFillBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fillColorClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillColorClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fillColorClicked

    private void setProperty(Element borderProperties, String attribute, String value) {
        Element leftEdgeWidthElement = XMLUtils.getPropertyElement(borderProperties, attribute);
        leftEdgeWidthElement.getAttributeNode("value").setValue(value);
    }

    private void updateFillStyle(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFillStyle
        // TODO add your handling code here:
    }//GEN-LAST:event_updateFillStyle

    private void borderColorButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borderColorButtonClicked
        Color currentBackground = borderColorButton.getBackground();
        Color color = JColorChooser.showDialog(null, "Color Chooser", currentBackground);
        if (color != null) {
            borderColorButton.setIcon(null);
            borderColorButton.setContentAreaFilled(false);
            borderColorButton.setOpaque(true);
            borderColorButton.setBackground(color);
        }

        updateBorderStyle(null);
    }//GEN-LAST:event_borderColorButtonClicked

    private void updateBorderSize(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateBorderSize
        updateBorderStyle(null);
    }//GEN-LAST:event_updateBorderSize

    private void updateBorderStyle(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBorderStyle
        String style = (String) borderStyleBox.getSelectedItem();
        boolean borderEnabled = style != null && !style.equals("None");

        borderWidthBox.setEnabled(borderEnabled);
        borderColorButton.setEnabled(borderEnabled);

        Set widgets = widgetsAndProperties.keySet();

        for (Iterator it = widgets.iterator(); it.hasNext(); ) {
            IWidget widget = (IWidget) it.next();

            Element borderProperties = (Element) widgetsAndProperties.get(widget);

            if (style != null) {
                setProperty(borderProperties, "Border Style", style);
            }

            Color color = borderColorButton.getBackground();
            if (color != null) {
                setProperty(borderProperties, "Border Color", color.getRGB() + "");
            }

            if (!borderWidthBox.getText().equals("mixed")) {
                String widthText = borderWidthBox.getText().replaceAll("cm", "");

                double width = Double.parseDouble(widthText);
                borderWidthBox.setText(width + " cm");

                width = width * units;

                setProperty(borderProperties, "Border Width", (Math.round(width)) + "");
            }

            widget.setBorderAndBackgroundProperties(borderProperties);
        }

        designerPanel.repaint();
    }//GEN-LAST:event_updateBorderStyle

    public void setProperties(Map widgetsAndProperties) {
        this.widgetsAndProperties = widgetsAndProperties;

        String borderStyleToUse = null, borderWidthToUse = null, borderColorToUse = null, backgroundStyleToUse = null,
                backgroundColorToUse = null;

        /** iterate through the widgets */
        for (Iterator it = widgetsAndProperties.keySet().iterator(); it.hasNext(); ) {
            IWidget widget = (IWidget) it.next();

            Element borderProperties = (Element) widgetsAndProperties.get(widget);

            /** add borders properties */
            Element border = (Element) borderProperties.getElementsByTagName("borders").item(0);

            String borderStyle = XMLUtils.getAttributeFromChildElement(border, "Border Style");
            String borderWidth = XMLUtils.getAttributeFromChildElement(border, "Border Width");
            String borderColor = XMLUtils.getAttributeFromChildElement(border, "Border Color");

            /** add background fill properties */
            Element background = (Element) borderProperties.getElementsByTagName("backgroundfill").item(0);

            String backgroundStyle = XMLUtils.getAttributeFromChildElement(background, "Style");
            String backgroundColor = XMLUtils.getAttributeFromChildElement(background, "Fill Color");

            if (borderStyleToUse == null) { // this must be the first time round
                borderStyleToUse = borderStyle;
                borderWidthToUse = borderWidth;
                borderColorToUse = borderColor;
                backgroundStyleToUse = backgroundStyle;
                backgroundColorToUse = backgroundColor;
            } else {
                // check for subsequent widgets
                if (!borderStyleToUse.equals(borderStyle))
                    borderStyleToUse = "mixed";

                if (!borderWidthToUse.equals(borderWidth))
                    borderWidthToUse = "mixed";

                if (!borderColorToUse.equals(borderColor))
                    borderColorToUse = "mixed";

                if (!backgroundStyleToUse.equals(backgroundStyle))
                    backgroundStyleToUse = "mixed";

                if (!backgroundColorToUse.equals(backgroundColor))
                    backgroundColorToUse = "mixed";
            }
        }

        /** set borders properties */
        setComboValue(borderStyleBox, borderStyleToUse.equals("mixed") ? null : borderStyleToUse);

        boolean borderEnabled = !borderStyleToUse.equals("None");
        borderWidthBox.setEnabled(borderEnabled);
        borderColorButton.setEnabled(borderEnabled);

        double width = Integer.parseInt(borderWidthToUse);
        width = round(width / units, 3);
        borderWidthBox.setText(width + " cm");

        setButtonColor(borderColorToUse, borderColorButton);

        /** set background fill properties */
        setComboValue(backgroundFillBox, backgroundColorToUse.equals("mixed") ? null : backgroundColorToUse);
        setButtonColor(backgroundColorToUse, backgroundFillColorButton);
    }

    private double round(double number, int decPlaces) {
        double exponential = Math.pow(10, decPlaces);

        number *= exponential;
        number = Math.round(number);
        number /= exponential;

        return number;
    }

    private void setButtonColor(String borderColorToUse, JButton button) {
        if (borderColorToUse.equals("mixed")) {
            BufferedImage bi = new BufferedImage(button.getWidth(), button.getHeight(), BufferedImage.TYPE_INT_ARGB);
            Graphics2D g2 = (Graphics2D) bi.getGraphics();
            g2.setColor(Color.red);
            g2.drawLine(-1, 0, bi.getWidth() - 1, bi.getHeight());
            g2.drawLine(-1, bi.getHeight() - 1, bi.getWidth() - 1, -1);

            button.setContentAreaFilled(true);
            button.setBackground(null);
            button.setIcon(new ImageIcon(bi));
        } else {
            button.setIcon(null);
            button.setContentAreaFilled(false);
            button.setOpaque(true);
            button.setBackground(new Color(Integer.parseInt(borderColorToUse)));
        }
    }

    private void setComboValue(JComboBox comboBox, Object value) {
        ActionListener listener = comboBox.getActionListeners()[0];
        comboBox.removeActionListener(listener);
        comboBox.setSelectedItem(value);
        comboBox.addActionListener(listener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox backgroundFillBox;
    private javax.swing.JButton backgroundFillColorButton;
    private javax.swing.JButton borderColorButton;
    private javax.swing.JComboBox borderStyleBox;
    private javax.swing.JTextField borderWidthBox;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel leftEdgesIcon;
    // End of variables declaration//GEN-END:variables

}
    

